/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "arith.h"
#include "tdd_common.h"
#include "util.h"
#include <stdlib.h>
#include <time.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_PrintIPAddr(void);
extern void test_ReadIPAddr(void);
extern void test_macAddr_LegalStr(void);
extern void test_macAddr_NumToStr(void);
extern void test_macAddr_NumsEqual(void);
extern void test_macAddr_StrToNum(void);
extern void test_macAddr_StrIsZero(void);
extern void test_macAddr_StrIsNonZero(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test-network.c");
  RUN_TEST(test_PrintIPAddr, 23);
  RUN_TEST(test_ReadIPAddr, 46);
  RUN_TEST(test_macAddr_LegalStr, 140);
  RUN_TEST(test_macAddr_NumToStr, 205);
  RUN_TEST(test_macAddr_NumsEqual, 221);
  RUN_TEST(test_macAddr_StrToNum, 246);
  RUN_TEST(test_macAddr_StrIsZero, 304);
  RUN_TEST(test_macAddr_StrIsNonZero, 332);

  return (UnityEnd());
}
